#!/bin/bash

# List of names
names=(
  Adam
  Christian
  Dorian
  Felix
  Hanna
  Isabell
  Johannes
  Julia
  Kristbjorg
  Kristina
  Lucie
  Marc
  Margaux
  Marius
  Michael
  Nina
  Paula
  Samuli
  Silje
  Solal
  Sylvain
  Thomas
  Trym
  Victor
  Zoe
)

# Path to the notebook to copy
notebook="basics_of_gridding.ipynb"

# Loop through the names and copy the file
for name in "${names[@]}"; do
  user="jupyter_${name}_lm25"
  user_home="/home/$user"

  if [ -d "$user_home" ]; then
    cp "$notebook" "$user_home/"
    echo "Copied $notebook to $user_home"
  else
    echo "Home directory $user_home does not exist. Skipping $user."
  fi
done

